# Generated by Django 5.2.7 on 2025-11-19 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UsuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('NumeroTelefono', models.CharField(blank=True, max_length=20, null=True)),
                ('CorreoElectronico', models.EmailField(max_length=255, unique=True)),
                ('Rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Técnico', 'Técnico'), ('Soporte', 'Soporte/Oficina')], default='Técnico', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ClienteID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreComercial', models.CharField(max_length=255)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Correo', models.CharField(blank=True, max_length=255, null=True)),
                ('Calle', models.CharField(blank=True, max_length=255, null=True)),
                ('NumeroExterior', models.CharField(blank=True, max_length=20, null=True)),
                ('Interior', models.CharField(blank=True, max_length=20, null=True)),
                ('Colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('CodigoPostal', models.CharField(blank=True, max_length=10, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('Pais', models.CharField(blank=True, max_length=100, null=True)),
                ('Ubicacion', models.TextField(blank=True, null=True, verbose_name='Link Google Maps')),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('ActividadID', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('Inicio', models.TimeField(blank=True, null=True)),
                ('Fin', models.TimeField(blank=True, null=True)),
                ('Estado', models.CharField(blank=True, max_length=50, null=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('PersonalAsignado', models.ForeignKey(db_column='PersonalAsignadoID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Cliente', models.ForeignKey(db_column='ClienteID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.clientes')),
            ],
            options={
                'db_table': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='OrdenesServicio',
            fields=[
                ('OrdenID', models.AutoField(primary_key=True, serialize=False)),
                ('TelefonoContacto', models.CharField(blank=True, max_length=20, null=True)),
                ('EmailContacto', models.CharField(blank=True, max_length=255, null=True)),
                ('Servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('Giro', models.CharField(choices=[('Energia', 'Energia'), ('Servicios residencial', 'Servicios residencial'), ('Linea comercial', 'Linea comercial'), ('Linea industrial', 'Linea industrial'), ('Unidades de refrigeración', 'Unidades de refrigeración'), ('Equipos electrogenos', 'Equipos electrogenos')], default='Servicios residencial', max_length=100)),
                ('Ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('FallaReportada', models.TextField(blank=True, null=True)),
                ('Programada', models.DateTimeField(blank=True, null=True)),
                ('Precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Terminada', 'Terminada')], default='Pendiente', max_length=50)),
                ('ClienteEmpresa', models.ForeignKey(db_column='ClienteEmpresaID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.clientes')),
                ('PersonalAsignado', models.ForeignKey(db_column='PersonalAsignadoID', limit_choices_to={'Rol': 'Técnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OrdenesServicio',
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalles',
            fields=[
                ('DetalleID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('Producto', models.CharField(blank=True, max_length=255, null=True)),
                ('InformacionAdicional', models.TextField(blank=True, null=True)),
                ('Orden', models.ForeignKey(db_column='OrdenID', on_delete=django.db.models.deletion.CASCADE, to='servicios.ordenesservicio')),
            ],
            options={
                'db_table': 'OrdenDetalles',
            },
        ),
        migrations.CreateModel(
            name='RegistrosTecnicos',
            fields=[
                ('RegistroID', models.AutoField(primary_key=True, serialize=False)),
                ('TipoUnidad', models.CharField(blank=True, max_length=100, null=True)),
                ('Marca', models.CharField(blank=True, max_length=100, null=True)),
                ('Modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('Capacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('TipoGasRefrigerante', models.CharField(blank=True, max_length=50, null=True)),
                ('InstalacionCondensador', models.CharField(blank=True, max_length=100, null=True)),
                ('ServicioRealizado', models.CharField(blank=True, max_length=255, null=True)),
                ('DistanciaEvap', models.CharField(blank=True, max_length=50, null=True)),
                ('DistanciaAlimentacion', models.CharField(blank=True, max_length=50, null=True)),
                ('CalibreCableado', models.CharField(blank=True, max_length=50, null=True)),
                ('TamanoHabitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('Desague', models.CharField(blank=True, max_length=100, null=True)),
                ('PresionGasRefrig', models.CharField(blank=True, max_length=50, null=True)),
                ('VoltajeAlimentacion', models.CharField(blank=True, max_length=50, null=True)),
                ('VoltajeTerminalesCond', models.CharField(blank=True, max_length=50, null=True)),
                ('TempHabitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('TempDescarga', models.CharField(blank=True, max_length=50, null=True)),
                ('BombaVacio', models.CharField(blank=True, max_length=50, null=True)),
                ('TiempoVacio', models.CharField(blank=True, max_length=50, null=True)),
                ('CapacitorCompresor_Original', models.CharField(blank=True, max_length=50, null=True)),
                ('CapacitorCompresor_Actual', models.CharField(blank=True, max_length=50, null=True)),
                ('CapacitorVentilador_Original', models.CharField(blank=True, max_length=50, null=True)),
                ('CapacitorVentilador_Actual', models.CharField(blank=True, max_length=50, null=True)),
                ('AmpTerminalesCompresor_Original', models.CharField(blank=True, max_length=50, null=True)),
                ('AmpTerminalesCompresor_Actual', models.CharField(blank=True, max_length=50, null=True)),
                ('SensorPozo_Original', models.CharField(blank=True, max_length=50, null=True)),
                ('SensorPozo_Actual', models.CharField(blank=True, max_length=50, null=True)),
                ('SensorAmbiente_Original', models.CharField(blank=True, max_length=50, null=True)),
                ('SensorAmbiente_Actual', models.CharField(blank=True, max_length=50, null=True)),
                ('ObservacionesTexto', models.TextField(blank=True, max_length=6000, null=True)),
                ('Satisfaccion', models.IntegerField(blank=True, null=True)),
                ('ComentarioCliente', models.TextField(blank=True, null=True)),
                ('NotasInternas', models.TextField(blank=True, null=True)),
                ('MaterialesUtilizados', models.JSONField(blank=True, null=True)),
                ('FirmaCliente', models.ImageField(blank=True, null=True, upload_to='firmas/clientes/')),
                ('FirmaTecnico', models.ImageField(blank=True, null=True, upload_to='firmas/tecnicos/')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Orden', models.OneToOneField(db_column='OrdenID', on_delete=django.db.models.deletion.CASCADE, to='servicios.ordenesservicio')),
                ('Tecnico', models.ForeignKey(db_column='TecnicoID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registrostecnicos',
            },
        ),
        migrations.CreateModel(
            name='RegistroFotos',
            fields=[
                ('FotoID', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(upload_to='fotos/registros/')),
                ('Descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('Registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicios.registrostecnicos')),
            ],
            options={
                'db_table': 'RegistroFotos',
            },
        ),
    ]
