# Generated by Django 5.2.7 on 2025-11-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Ubicacion',
            field=models.TextField(blank=True, null=True, verbose_name='Enlace Google Maps'),
        ),
    ]
