# Generated by Django 5.2.7 on 2025-11-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_clientes_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesservicio',
            name='Giro',
            field=models.CharField(blank=True, choices=[('Energia', 'Energia'), ('Servicios residencial', 'Servicios residencial'), ('Linea comercial', 'Linea comercial'), ('Linea industrial', 'Linea industrial'), ('Unidades de refrigeración', 'Unidades de refrigeración'), ('Equipos electrogenos', 'Equipos electrogenos')], max_length=100, null=True),
        ),
    ]
