# Generated by Django 5.2.7 on 2025-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_ordenesservicio_giro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenesservicio',
            name='Fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin Real'),
        ),
        migrations.AddField(
            model_name='ordenesservicio',
            name='Inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio Real'),
        ),
    ]
